# Made by MrRafter
# Dupe Made For Hispanarky
# If you have any problems please contact me through discord: MrRafter_#4660

enable:
  dispenser: true
  dropper: true
settings:
  probability: 100
  cooldown: 1
